### ISSUE TITLE
Unable to generate constant int(32)

### ISSUE THREAD

**Issue by msievers** [feliixx/mgodatagen#15]
Hi!

First of all, thank you for this neat little tool. It really fills a gap.

I have one problem. I cannot generate a constant int value.

The use case is to generate documents with a field `version`, always set to `0`. Using the int32 generator I must use `maxInt` > `minInt`. Using constant generator and supplying 0, it generates a double `1.0`.

Any suggestions on this?

Thx in advance!

**Comment by feliixx** [comment]
Hi, thanks for the report! Indeed it wasn't possible, I've updated the Numbers Generators to allow this. 

you can now use an `Int` generator like this: 
```
"version": {
  "type": "int"
  "minInt": 0,
  "maxInt": 0
}
```

or just (`minInt` and `maxInt` default to 0)
```
"version": {
  "type": "int"
}
```
This should work for `Int`, `Long` and `Double` generators

**Comment by msievers** [comment]
Awesome. This was fast :)

I really appreciate this. I have shown your tool to some colleges of mine and everybody I showed it so far was very interested.

Thanks a lot!
