### ISSUE TITLE
unrecognized import

### ISSUE THREAD

**Issue by adrian-goe** [feliixx/mgodatagen#28]
Hello, I tried to rebuild my docker image today. I always get the following error.

```
Step 15/16 : RUN go get -u "github.com/feliixx/mgodatagen"
 ---> Running in 23c7fe93e440
unrecognized import path "go.mongodb.org/mongo-driver/bson/mgocompat": reading https://go.mongodb.org/mongo-driver/bson/mgocompat?go-get=1: 404 Not Found
The command '/bin/sh -c go get -u "github.com/feliixx/mgodatagen"' returned a non-zero code: 1
```

The corresponding part in the docker file looks like this
```
...
RUN wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
RUN tar -xvf go1.14.1.linux-amd64.tar.gz
RUN mv go /usr/local
RUN go get -u "github.com/feliixx/mgodatagen"
...
```

Do you have any idea what might be causing it?

**Comment by feliixx** [comment]
Hi @adrian-goe, thanks for the report ! For some reason, the mongodb repo is missing this package. Looks like a bug, but in the meantime, you can try this: 

Setting GOPROXY env variable to https://proxy.golang.org/ ( `export GOPROXY=https://proxy.golang.org/` )

or instead, clone the repo and build it: 

```
git clone https://github.com/feliixx/mgodatagen
cd mgodatagen 
go build 
```

hope this helps !
