### ISSUE TITLE
Failing to create unique indexes

### ISSUE THREAD

**Issue by 15astro** [feliixx/mgodatagen#32]
I am trying to create collection with unique index. mgodatagen is creating the data first and then creating unique index.

Having duplicate records already in collection causing createIndex call to fail with `cause: E11000 duplicate key error collection`

**Comment by feliixx** [comment]
hi @15astro, in order to create index only, you should use the `--indexonly` flag, for example: 

`mgodatagen -f config.json --indexonly`

Hope this helps !

**Comment by 15astro** [comment]
The idea here is to not only create indexes but to provide config that has `content` & `indexes` specified in the config file passed to mgodatagen. The expected output will be a collection with data and required indexes.

The noticed behavior creates the data first and create indexes. Causing unique index creation to fail as the duplicate data is getting created in the data generation part.

If --indexOnly is passed is used, the unique index creation is going to fail eventually due to duplicate data.

**Comment by feliixx** [comment]
Sorry for the misunderstanding, there is now a new flag (`-x | --indexfirst` ) to create index before inserting documents. This feature is available in version [0.8.2](https://github.com/feliixx/mgodatagen/releases/tag/v0.8.2), please let me know if this solves your problem !
