### ISSUE TITLE
Array having size=0 cannot be generated

### ISSUE THREAD

**Issue by visko-sc** [feliixx/mgodatagen#53]
Having this template:
```
[
  {
    "collection": "collection",
    "count": 1,
    "content": {
      "users": {
        "type": "array",
        "size": 0
      }
    }
  }
]
```
The actual result is:
```
error in configuration:
  fail to create collection collection: invalid generator for field 'key'
  cause: make sure that 'size' >= 0
```
And the expected result:
```
[
  {
    "_id": ObjectId("5a934e000102030405000000"),
    "users": []
  }
]
```
I can see a bug in collinfo.go:542 (it should be `if config.Size < 0`), but even if that is fixed, an "arrayContent" is also required in line 545 which would be unnecessary for an empty array.

**Comment by feliixx** [comment]
thanks for the report, it should work fine with the new release: [version 0.9.1](https://github.com/feliixx/mgodatagen/releases/tag/v0.9.1)
