### ISSUE TITLE
Add a constant ObjectId

### ISSUE THREAD

**Issue by curioustushar** [feliixx/mgodatagen#54]
- Generate data with this configuration

```
"test_objectid": {
	"type": "constant",
	"constVal": {
	  "$oid": "5a934e000102030405000001"
	}
}
```

https://mongoplayground.net/p/kLGsx6V2bHY

Output

```
  {
    "_id": ObjectId("5a934e000102030405000000"),
    "test_objectid": {
      "$oid": "5a934e000102030405000001"
    }
  }
```

`test_objectid` is saved as `{ "$oid": "5a934e000102030405000001" }`, it doesn't converts to ObjectId.

<hr>

- Create a document 

```
[
  {
    "test_objectid": {
      "$oid": "5a934e000102030405000001"
    }
  }
]
```

https://mongoplayground.net/p/2qIZHXMG561

Output is correct

```
[
  {
    "_id": ObjectId("5a934e000102030405000000"),
    "test_objectid": ObjectId("5a934e000102030405000001")
  }
]
```

<hr>

- Workaround

```
db.collection.find({}).toArray()
  .forEach(function (doc) {
    try { doc.test_objectid = ObjectId( doc.test_objectid.$oid ) } catch(e) {} // convert manually
    db.collection.save(doc);
  });

```

**Comment by feliixx** [comment]
Hi @curioustushar 

thanks for the report, it shoudl work fine with the new release: [version 0.9.1](https://github.com/feliixx/mgodatagen/releases/tag/v0.9.1)

**Comment by curioustushar** [comment]
@feliixx Thank you for the quick work on that, but it doesn't seem to work with JSON so I've raised PR #57 with a fix.

Note- This is my 1st piece of code in go, so I'm not sure it's the correct way or not but it works.

I feel so happy writing Golang for the 1st time, it was fun. I had to fiddle around but glad my efforts paid off.

Please do give feedback :smiley: 

Thank you :+1:
