### ISSUE TITLE
followed the instructions but does not work at all

### ISSUE THREAD

**Issue by alexmlopez** [feliixx/mgodatagen#58]
Foollowed your install instructions ,and there are not build files, for go to execute .

files:
codecov.yml  datagen  demo.gif  go.mod  go.sum  LICENSE  main.go  README.md  test.sh

go install will not generate any ./mgodatagen executable

**Comment by feliixx** [comment]
Hi @alexmlopez, 

`go install` compile the executable and move it to your `GOBIN` path. If you want to build the executable in the directory, 
use `go build` instead

Hope this helps
