### ISSUE TITLE
Array of Random Length/Size

### ISSUE THREAD

**Issue by JRagone** [feliixx/mgodatagen#59]
Thanks for making this!

Is it possible to create an array of random length? Something along these lines is what I'm looking for:

```js
"fieldName": {
    "type":             "array",     // required
    "size":             `randomInt`, // required, size of the array
    "arrayContent":     `generator`, // generator use to create element to fill the array.
                                     // can be of any type
    "nullPercentage":   `int`,       // optional
    "maxDistinctValue": `int`        // optional
}
```

**Comment by feliixx** [comment]
Hi @JRagone, 

currently it's not possible to create an array of random length, but it should be fairly easy to add this feature. Would you be interested in implementing it ? 

A solution would be to add two new attributes for array;  `minSize` and `maxSize`

**Comment by JRagone** [comment]
Sure! It might take me a few weeks to get around to it, but I'll open a PR once I have something working.

**Comment by feliixx** [comment]
Hi @JRagone , 

I've just released a new version with this feature: [version 0.9.2](https://github.com/feliixx/mgodatagen/releases/tag/v0.9.2)
