### ISSUE TITLE
Generate UUID as binary

### ISSUE THREAD

**Issue by arn-cpu** [feliixx/mgodatagen#60]
Hello,

is there an option for generator to generate UUID as binary (not as string)? 

For example this is how you would write binary UUID to use in mongoimport/mongoexport:
```
{
                  "$binary": {
                    "base64": "zggG33O7Tgiaf0MIfkBp/g==",
                    "subType": "04"
                  }
                }
```
Then in MongoCompass is shown as _UUID('3508bdf2-b598-44a4-918c-4966e54a4d27')_, not as simple string.
This is common practice for i.e. MongoDB Java Driver, it would be very useful to make it possible in this generator with ids, fields, references etc.

**Comment by feliixx** [comment]
Hi @arn-cpu, 

I just implemented it. To create a binary UUID, use this generator: 

```
"field": {
  "type":    "uuid",
  "format": "binary" 
}
```
