### ISSUE TITLE
fromArray ObjectId

### ISSUE THREAD

**Issue by pipaliyachirag** [feliixx/mgodatagen#65]
hi is it possible to pass array of ObjectId in fromArray in props?
if yes then can you please share demo code?

`"user": {
        "type": "fromArray",
        "in": [
          "6107c50de31053fa30380735",
          "6107c50de31053fa30380736",
          "6107c50de31053fa30380737",
          "6107c50de31053fa30380738",
          "6107c50de31053fa30380739",
          "6107c50de31053fa3038073a",
          "6107c50de31053fa3038073b",
          "6107c50de31053fa3038073c",
          "6107c50de31053fa3038073d",
          "6107c50de31053fa3038073e",
          "6107c50de31053fa3038073f",
          "6107c50de31053fa30380740",
          "6107c50de31053fa30380741",
          "6107c50de31053fa30380742",
          "6107c50de31053fa30380743",
          "6107c50de31053fa30380744",
          "6107c50de31053fa30380745",
          "6107c50de31053fa30380746",
          "6107c50de31053fa30380747",
          "6107c50de31053fa30380748"
        ],
        "randomOrder": true
      }`

**Comment by feliixx** [comment]
Hi @pipaliyachirag, 

yes, you need to use mongodb extended JSON v2 like this: 
```

[
  {
    "collection": "collection",
    "count": 10,
    "content": {
      "user": {
        "type": "fromArray",
        "in": [
          {
            "$oid": "6107c50de31053fa30380735"
          },
          {
            "$oid": "6107c50de31053fa30380736"
          },
          {
            "$oid": "6107c50de31053fa30380737"
          },
          {
            "$oid": "6107c50de31053fa30380738"
          },
          {
            "$oid": "6107c50de31053fa30380739"
          }
        ],
        "randomOrder": true
      }
    }
  }
]
```


you can try it here: https://mongoplayground.net/p/_4DLNiMvwBj

**Comment by pipaliyachirag** [comment]
Thank you.
