### ISSUE TITLE
add basic generator type Enum

### ISSUE THREAD

**Issue by visko-sc** [feliixx/mgodatagen#74]
It would be great to have an Enum type basic generator:
```
"fieldName": {
  "type":             "enum",
  "values":        ["Taurus", "Cancer", "Virgo", ..]
}
```

**Comment by feliixx** [comment]
Hi @visko-sc, 

you can use the `fromArray` generator to achieve this: 

```
"fieldName": {
  "type":             "fromArray",
  "in":        ["Taurus", "Cancer", "Virgo"]
}
```

see for example: https://mongoplayground.net/p/qwo5JYhOBrR

**Comment by idc77** [comment]
I agree though that the term enum is more recognizable and standardized than fromArray
