### ISSUE TITLE
Fields order of compound indexes is not respected

### ISSUE THREAD

**Issue by pplr** [feliixx/mgodatagen#82]
In a configuration containing the following index:
```
{ "key": {
  "suID": 1,
  "dvID": 1,
  "tm": 1
 },
 "name": "suID_1_dvID_1_tm_1"
}
```
the following index was created:
```
{ "key": {
  "tm": 1,
  "suID": 1,
  "dvID": 1
 },
 "name": "suID_1_dvID_1_tm_1"
}
```

**Comment by pplr** [comment]
Changing the Index struct using `bson.D` for the Key field fixes this issue but it also changes the json format:
```
{ "key": [
 { "key":  "suID", "value" : 1},
 { "key": "dvID", "value": 1},
 { "key": "tm", "value": 1}
 },
 "name": "suID_1_dvID_1_tm_1"
}
```

**Comment by feliixx** [comment]
Hi @pplr, thanks for the report. I'll cut a new release with the fix in the folowing days
