### ISSUE TITLE
neted objectContent greater than 1

### ISSUE THREAD

**Issue by galinrustem** [feliixx/mgodatagen#89]
It is possible to make nested objects greater than 1, for example, by the parameter "objectContentCount"
so that according to this configuration

[{"database":"db",
 "collection":"cd_card_tree",
 "count":1,
 "content":{
  "id_cleint":{"type":"long","maxLong":999999999999}, 
  "id_card":{"type":"object", "objectContentCount":2, "objectContent":{
	 "card_no":{"type":"long","maxLong":9999999999}, 
     "card_date":{"type":"date"}, 
     "transaction":{"type":"object", "objectContentCount":2, "objectContent":{
	   "tran_sum":{"type":"decimal"}, 
       "tran_date":{"type":"date"}}
	  }
	 }
	}
  }
 }]
 
to make it work, this is the result
[
   {
    "_id": ObjectId("5a934e000102030405000001"),
	"id_cleint": NumberLong(863926077139),
    "id_card":[{
      "card_date": "2021-10-01",
      "card_no": NumberLong(1539691641),
      "transaction":[ 
	  {
        "tran_date": "2022-03-11",
        "tran_sum": 100.0
      }, 
	  {
        "tran_date": "2022-03-11",
        "tran_sum": 200.0
      }]
    },
	{
      "card_date": "2021-11-21",
      "card_no": NumberLong(4539691641),
      "transaction":[ 
	  {
        "tran_date": "2022-03-11",
        "tran_sum": 100.0
      }, 
	  {
        "tran_date": "2022-03-11",
        "tran_sum": 200.0
      }]
    }]
  }
]

**Comment by feliixx** [comment]
you need to use an `array` generator for this:

```
[
  {
    "database": "db",
    "collection": "cd_card_tree",
    "count": 1,
    "content": {
      "id_client": {
        "type": "long",
        "maxLong": 999999999999
      },
      "id_card": {
        "type": "array",
        "minLength": 2,
        "maxLength": 2,
        "arrayContent": {
          "type": "object",
          "objectContent": {
            "card_no": {
              "type": "long",
              "maxLong": 9999999999
            },
            "card_date": {
              "type": "date"
            },
            "transaction": {
              "type": "array",
              "minLength": 2,
              "maxLength": 2,
              "arrayContent": {
                "type": "object",
                "objectContent": {
                  "tran_sum": {
                    "type": "decimal"
                  },
                  "tran_date": {
                    "type": "date"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```


you can try it here: [mongoplayground.net/p/NxMxni8rnKj](https://mongoplayground.net/p/NxMxni8rnKj)
