### ISSUE TITLE
`int` generator without further configuration always generates `0`

### ISSUE THREAD

**Issue by msievers** [feliixx/mgodatagen#93]
Hi!

Maybe this one is somehow related to https://github.com/feliixx/mgodatagen/issues/92

Having the following configuration file

```json
[
  {
    "database": "someDatabase",
    "collection": "someCollection",
    "count": 10,
    "content": {
      "someInt": {
        "type": "int"
      }
    }
  }
]
```

what I get in the database is the following

![Screenshot from 2022-09-01 12-01-38](https://user-images.githubusercontent.com/156371/187888882-795bac0f-dc44-4d69-9b22-739209c09347.png)

I already noticed something similar with the `string` generator, where I needed to specify `minLength` and `maxLength`, or else I got the empty string all the time.

As soon as one adds `minInt` and `maxInt` it starts to generate values other then `0`. This is also similiar to how `string` generator behaves, as it starts to generate values as soon as `minLength` and `maxLength` are given. Unfortnuatly this does not help with `stringFromParts` (see #92)

See the following playground for an interactive example for `int`:

https://mongoplayground.net/p/u_dNIJBpf3R

And here for `string` without further configuration:

https://mongoplayground.net/p/yxQ3BcABvlV

**Comment by feliixx** [comment]
I've been thinking about this and indeed it can be improved

I've updated the code to set default bounds if none are present in version [0.11.0](https://github.com/feliixx/mgodatagen/releases/tag/v0.11.0)
